export const POST_PICTURE_REQUESTED = 'POST_PICTURE_REQUESTED'
export const POST_PICTURE_SUCCEEDED = 'POST_PICTURE_SUCCEEDED'
export const POST_PICTURE_FAILED = 'POST_PICTURE_FAILED'

export const PUT_PICTURE_REQUESTED = 'PUT_PICTURE_REQUESTED'
export const PUT_PICTURE_SUCCEEDED = 'PUT_PICTURE_SUCCEEDED'
export const PUT_PICTURE_FAILED = 'PUT_PICTURE_FAILED'
